remote_theme: b2a3e8/jekyll-theme-console
header_pages:
  - index.md
  - about.md

style: dark
listen_for_clients_preferred_style: false

footer: 'follow us on <a href="https://twitter.com/xxx">twitter</a>'
